### ISSUE TITLE
Improved superclops behavior

### ISSUE THREAD

**Issue by richtaur** [lostdecade/onslaught_arena#40]
Make him more "bossy"!

**Comment by richtaur** [comment]
- Rush out of the gate.
- Improve projectiles: either like, knives used to be? |/ or like ping ping ping, three in a row.
- lolz

**Comment by geoffb** [comment]
Fixed by https://github.com/lostdecade/onslaught/commit/5a463900c9ed6b054a81947e9ce2b79cc25fd727

Phase 1: Rush out of the gates to middle of arena.
Phase 2: Wiggle for 1.5s, indicating something big!
Phase 3: Unleash 8 bouncing boulders in a circular pattern
Phase 4: Chase Xam, tossing energy balls for 6s.
Rinse. Repeat starting at 2.
